#!/usr/bin/env bash
#Group by IP and HTTP code, count occurences, and sort descending
awk '{count[$1,$9]++} END {for (key in count) {split(key, arr, SUBSEP); printf "%6d %s %s\n", count[key], arr[1], arr[2]}}' apache-access.log | sort -rn
