#!/usr/bin/env bash
#This script return with decision whether the file exists or not.

#check if the file/directory 'school' exists
if [ -e school ]; then
echo "school file exists"

check if it is empty
if [ ! -s school ]; then
echo "school file is empty"
else
echo "school file is not empty"
fi

#Check if it is a regular file
if [ -f school ]; then
echo "school is a regular file"
fi 

else
echo "school file does not exist"
fi
